version: '3.7'

services:
        inari-web:
                build:
                        dockerfile: Dockerfile
                volumes:
                        - ~/photos_inari_mediastore:/tmp/inari
                        - ~/photos_inari_mediastore/thumbnails:/var/media/thumbnails
                ports:
                        - 8080:80
