services:
        loadbalancer:
                build:
                        context: ./apps/nginx/
                ports:
                        - 8010:80
                depends_on:
                        - inari-ui

        inari-api:
                build:
                        context: ./apps/api/
                volumes:
                        - /mnt/data/backup/jayr/inari_mediastore:/tmp/inari
                        - /mnt/data/backup/jayr/inari_mediastore/thumbnails:/var/media/thumbnails
                depends_on:
                        - geo2tz
                environment:
                        - AWS_ACCESS_KEY_ID
                        - AWS_SECRET_ACCESS_KEY
                        - AWS_DEFAULT_REGION

        inari-ui:
                build:
                        context: ./apps/ui

        geo2tz:
                container_name: geo2tz
                image: ghcr.io/noandrea/geo2tz:2.1.4
                ports:
                        - 2004:2004
