version: '3.7'

services:
        inari-api:
                build:
                        dockerfile: ./apps/api/Dockerfile
                volumes:
                        - /mnt/data/backup/jayr/inari_mediastore:/tmp/inari
                        - /mnt/data/backup/jayr/inari_mediastore/thumbnails:/var/media/thumbnails
                ports:
                        - 8010:80

        inari-ui:
                build:
                        context: ./apps/ui

        geo2tz:
                container_name: geo2tz
                image: ghcr.io/noandrea/geo2tz:2.1.4
                ports:
                        - 2004:2004

        inari-api-test:
                build:
                        dockerfile: ./apps/api/Dockerfile-test
                volumes:
                        - ./apps/api:/inari
                        - $GOPATH/pkg/mod:/go/pkg/mod

        inari-ui-test:
                build:
                        dockerfile: ./apps/ui/Dockerfile-test
                volumes:
                        - ./apps/ui:/app
