version: '3.7'

services:
        inari-api:
                build:
                        dockerfile: ./apps/api/Dockerfile
                volumes:
                        - ~/photos_inari_mediastore:/tmp/inari
                        - ~/photos_inari_mediastore/thumbnails:/var/media/thumbnails
                ports:
                        - 8010:80

        inari-ui:
                build:
                        context: ./apps/ui
