version: '3.7'

services:
        deployer:
                build:
                        dockerfile: Dockerfile
                        context: apps/deployer
                working_dir: /app
                volumes:
                        - ./apps:/app/apps:ro
                environment:
                        PROJECT_NAME: inari
                        CURRENT_ENV: dev
                        AWS_REGION: ${AWS_REGION}
                        AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

        api:
                build:
                        dockerfile: Dockerfile
                        context: apps/api
                working_dir: /app
                volumes:
                        - ./apps/api:/app:rw

        ui:
                build:
                        dockerfile: Dockerfile
                        context: apps/ui
                working_dir: /app
                volumes:
                        - ./apps/ui:/app:rw

        acceptance:
                image: testcafe/testcafe
                volumes:
                        - ./apps/acceptance-tests/tests:/tests:rw
