version: '3.7'

services:
        api:
                build:
                        dockerfile: Dockerfile
                        context: apps/api
                working_dir: /app
                volumes:
                        - ./apps/api:/app:rw
