AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB datastore

Parameters:
  EnvironmentName:
    Description: The environment name
    Type: String
    Default: dev
    AllowedPattern: ^(dev|prod)$

Resources:
  InariDatastore:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
        - AttributeName: "gsi1pk"
          AttributeType: "S"
        - AttributeName: "gsi1sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "GSI1"
          Projection:
            ProjectionType: "ALL"
          KeySchema:
            - AttributeName: "gsi1pk"
              KeyType: "HASH"
            - AttributeName: "gsi1sk"
              KeyType: "RANGE"
