service: funabashi-photos
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1
  httpApi:
    id: ${env:APIGATEWAYID, ''}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "dynamodb:Query"
          Resource:
            - "arn:aws:dynamodb:eu-central-1:725941804651:table/inari-dynamodb-dev-InariDatastore-1VAD7YFUNHWKE"
            - "arn:aws:dynamodb:eu-central-1:725941804651:table/inari-dynamodb-dev-InariDatastore-1VAD7YFUNHWKE/*"

        - Effect: "Allow"
          Action:
            - "s3:GetObject"
            - "s3:ListBucket"
          Resource:
            - "arn:aws:s3:::inari-mediastore-dev/*"
            - "arn:aws:s3:::inari-mediastore-dev/*"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            - "arn:aws:s3:::inari-thumbnailstore-dev/*"

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  timeline:
    handler: bin/timeline
    events:
      - httpApi:
          method: GET
          path: /api/months
          authorizer:
            type: jwt
            id: ${env:AUTHORIZERID, ''}

  timeline_month:
    handler: bin/timeline_month
    events:
      - httpApi:
          method: GET
          path: /api/month/{monthID+}
          authorizer:
            type: jwt
            id: ${env:AUTHORIZERID, ''}

  create_thumbnails:
    handler: bin/create_thumbnails
    events:
      - sqs:
          arn: !GetAtt CreateThumbnailQueue.Arn

resources:
  Resources:
    CreateThumbnailQueue:
      Type: AWS::SQS::Queue
      Properties:
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt CreateThumbnailDeadLetterQueue.Arn
          maxReceiveCount: 3

    CreateThumbnailDeadLetterQueue:
      Type: AWS::SQS::Queue
