service: funabashi-photos
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1
  httpApi:
    id: ${env:APIGATEWAYID, ''}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "dynamodb:Query"
          Resource: "arn:aws:dynamodb:eu-central-1:725941804651:table/inari-dynamodb-dev-InariDatastore-1VAD7YFUNHWKE"

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  timeline:
    handler: bin/timeline
    events:
      - httpApi:
          method: GET
          path: /api/timeline/{date+}
          authorizer:
            type: jwt
            id: ${env:AUTHORIZERID, ''}

#resources:
  #  Resources:
