FROM golang:alpine as build

WORKDIR /build
COPY . .
RUN go mod download
RUN go build -o inari cmd/cli/main.go

FROM alpine:latest

WORKDIR /

COPY --from=build /build/inari /inari

# RUN apk update && \
#     apk add bash
# 	exiftool

CMD [ "./inari" ]
