FROM golang:alpine as build

RUN apk update && \
    apk add \
    build-base

WORKDIR /build
COPY . .
RUN go mod download
RUN go build -o inari cmd/cli/main.go

FROM alpine:latest

RUN apk update && \
	apk add \
	exiftool \
    tzdata

WORKDIR /

COPY --from=build /build/inari /inari

CMD [ "./inari" ]
