name: build test deploy
on:
  push:
    braches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: make test
        
    - name: deploy
      run: make deploy
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
