name: build test deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ls -lhA;make test-api

  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/ui
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: test
        run: yarn test
