name: build test deploy
on:
  push:
    branches:
      - main
      - master

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: e2e test
        run: ./apps/api/scripts/e2e-test.sh
